/**
 * aboutData.js — About Me app data layer.
 *
 * All personal content is imported from src/content/portfolio.js.
 * Edit that file to update your portfolio — do not edit this file.
 *
 * This module re-exports what About Me components expect, maintaining
 * full backward compatibility with all existing component imports.
 */

export {
  IDENTITY as PROFILE,
  SOCIALS,
  SKILLS,
  TECH_STACK,
  EXPERIENCE,
  OPEN_SOURCE,
} from '@content/portfolio'
